# Generated by Django 6.0.2 on 2026-02-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("shop_name", models.CharField(max_length=120)),
                (
                    "drink_type",
                    models.CharField(
                        choices=[
                            ("latte", "Latte"),
                            ("espresso", "Espresso"),
                            ("cappuccino", "Cappuccino"),
                            ("americano", "Americano"),
                            ("flat_white", "Flat White"),
                            ("mocha", "Mocha"),
                            ("iced", "Iced Coffee"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="drink_images/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("name", "shop_name")},
            },
        ),
    ]
