# Generated by Django 2.2.28 on 2026-02-23 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('drink_type', models.CharField(choices=[('latte', 'Latte'), ('espresso', 'Espresso'), ('cappuccino', 'Cappuccino'), ('americano', 'Americano'), ('flat_white', 'Flat White'), ('mocha', 'Mocha'), ('iced', 'Iced Coffee'), ('other', 'Other')], default='other', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='drink_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drinks', to='shops.Shop')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'shop')},
            },
        ),
    ]
