# Generated by Django 4.2.11 on 2026-03-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shop_options_remove_shop_created_at_shop_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
