# Generated by Django 4.2 on 2026-03-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20260313_1343'),
        ('shops', '0005_remove_shop_latitude_remove_shop_longitude'),
    ]

    operations = [
    ]
